### ISSUE TITLE
Example returns error "Cannot read property 'length' of null"

### ISSUE THREAD

**Issue by gigerdo** [alexbol99/flatten-offset#1]
The example does not work for me. Am I doing something wrong here? Really no idea what the problem could be.

Code
```
import Flatten from "@flatten-js/core";
import {offset} from "@flatten-js/polygon-offset";
import Polygon = Flatten.Polygon;
import segment = Flatten.segment;
import point = Flatten.point;

// Create polygon
let shapes = [
    segment(point(200,100), point(200,300)),
    segment(point(200,300), point(440,300)),
    segment(point(440,300), point(300,200)),
    segment(point(300,200), point(440,150)),
    segment(point(440,150), point(500,150)),
    segment(point(500,150), point(640,200)),
    segment(point(640,200), point(500,300)),
    segment(point(500,300), point(740,300)),
    segment(point(740,300), point(740,100)),
    segment(point(740,100), point(200,100))
];

let polygon = new Polygon();
polygon.addFace(shapes);

// Apply polygon offset
let offsetPolygon = offset(polygon, 20);
```

Error:
```
project\node_modules\@flatten-js\polygon-offset\dist\main.cjs.js:177
        len = split[0].length;
                       ^
TypeError: Cannot read property 'length' of null
    at addToIntPoints (project\node_modules\@flatten-js\polygon-offset\dist\main.cjs.js:177:24)
    at getIntersections (project\node_modules\@flatten-js\polygon-offset\dist\main.cjs.js:157:17)
    at clip (project\node_modules\@flatten-js\polygon-offset\dist\main.cjs.js:72:25)
    at booleanOpBinary (project\node_modules\@flatten-js\polygon-offset\dist\main.cjs.js:63:12)
    at unify (project\node_modules\@flatten-js\polygon-offset\dist\main.cjs.js:34:20)
    at Object.offset (project\node_modules\@flatten-js\polygon-offset\dist\main.cjs.js:789:33)
    at Object.<anonymous> (project\scratch.ts:29:21)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Module.m._compile (project\node_modules\ts-node\src\index.ts:1043:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
```

**Comment by gigerdo** [comment]
The problem is because of a change of behavior in flatten-js: 
split() used to return a list with just one segment if the split-point is either end or start point of the segment. Now it returns [null, segment]. The bug is actually in flattenjs/boolean-op, and someone has reported it there as well: https://github.com/alexbol99/flatten-boolean-op/issues/17

I think upgrading to newest core version would be  best: #2
